<?php

$data = json_decode(file_get_contents(__DIR__ . "/Wichita_Transit_Routes.json"), true);
$routes = [];

foreach ($data["features"] as $route) {
  $id   = $route["properties"]["OBJECTID"];
  $name = $route["properties"]["NAME"];
  $routes[$id] = ["name" => $name, "geojson" => $route];
}

$json = json_encode($routes);
file_put_contents(
  "routes.js",
  "// Generated by make_routes.php\n" .
  "// Do not edit by hand.\n" .
  "routes = {$json};\n"
);
